### ISSUE TITLE
how to find properties of industrial common mixtures

### ISSUE THREAD

**Issue by oddtopus** [CalebBell/thermo#12]
Mr. @CalebBell, good morning.
First I'd like to thank You for the very accurate libraries that you shared in these repositories. When I knew about "fluids" I immediately tried to use it because me too have my own "itches to scratch": in fact now, inside the workbench for FreeCAD that I'm developing, there is a small utility to calculate pressure losses of pipes drawn with that same tool (up to now: only for tubes+elbows and only for liquid water).
Beside that, my question is related to the properties of some very common fluids used in industry like kerosene or hydraulic oils (HLP or CLP for instance) which I didn't find neither in Chemical() nor in Mixture().
Is there a way to define a custom fluid table (.csv) so that I can create an object simply with kerosene=thermo.Mixture("kerosene") or oil=thermo.Chemical('HLP68')?
Thank You

**Comment by CalebBell** [comment]
Hi oddtopus,
That sounds like a very interesting project! It would allow for some very impressive visualization of results. If you have any questions about calculating pressure drop (acceleration, two-phase, etc) please feel free to ask.

The thermo library is built around chemicals with discrete structures. Any mixture of known chemical components can be created, and properties attempted to be calculated for them. There is no theoretical limit to the number of compounds which can be in a mixture, and it is possible to add more chemicals to the database if they are missing. 
Unfortunately, if you don't know the composition you want to represent kerosene with, there is no way to get a property for it. The same goes double for hydraulic fluids - their composition is often proprietary. Because of how many of the correlations and models in thermo work, it is only possible to add chemicals with defined structures.
Good luck with flamingo!

**Comment by CalebBell** [comment]
I am closing this issue.

Thermo is very large as it is, and one project can't do everything. It's not a topic that interests me personally either. Others are free to write their own libraries, maybe even using Thermo.

Sincerely,
Caleb
