### ISSUE TITLE
Licenses/copyright status for data sources

### ISSUE THREAD

**Issue by non-Jedi** [CalebBell/thermo#16]
Hi Caleb,

I was wondering if there's a specific way you've documented the license or copyright status of the various tables in thermo? Looking through the modules, there's a lot of tsvs that get imported, but I'm not clear on what's required of me if I duplicate those in other projects (or if I'm allowed to in the first place).

Thanks,

Adam

**Comment by CalebBell** [comment]
Hi Adam,

I obviously cannot offer any legal advice of any kind, and I will not offer my opinions either. Copyright is different in every jurisdiction; however, if you ask a lawyer in any of them if the boiling point of water is copyrightable they will all laugh and say no. Another point is that calculated values that are the result of mechanical calculation are often not eligible for copyright in many jurisdictions; many tabulated values are calculated or the result of averaging. Some jurisdictions have "Database Rights" which do grant a special copyright to otherwise uncopyrightable data as well; the US does not (today) to my knowledge.

I always make sure to give clear attribution to all sources. This project as a whole is released under the MIT license. 

Cheers,
Caleb

**Comment by non-Jedi** [comment]
Thanks for the general info. :)
