### ISSUE TITLE
Incorrect Prandtl numbers

### ISSUE THREAD

**Issue by archeryguru2000** [CalebBell/thermo#20]
I'm not sure if this is worthy of an issue or not; however, as I'm comparing the results to numerous chemicals, I'm presented with incorrect Prandtl number values.  For example:
>>> co2 = Chemical('carbon dioxide')
>>> co2.calculate(T=50+273, P=101325)
>>> co2.Pr
0.6482332387082907
Expected to get 0.7520
>>> co = Chemical('carbon monoxide')
>>> co.calculate(T=50+273, P=101325)
>>> co.Pr
0.696779328644075
Expected to get 0.7328
>>> h2 = Chemical('hydrogen')
>>> h2.calculate(T=50+273, P=101325)
>>> h2.Pr
0.7689021940555787
Expected to get 0.7191
>>> n2 = Chemical('nitrogen')
>>> n2.calculate(T=50+273, P=101325)
>>> n2.Pr
0.6687213666959588
Expected to get 0.7114
>>> o2 = Chemical('oxygen')
>>> o2.calculate(T=50+273, P=101325)
>>> o2.Pr
0.6781361087948815
Expected to get 0.7053

... and, so on.  I'm curious of the expected accuracy of these values.  I admit, I'm simply looking these Prandtl numbers in textbook tables; however, several textbooks all show nearly the same values.  Thanks for any input/insight you may provide.

**Comment by archeryguru2000** [comment]
Also, after digging a little deeper, I've found more information.  When computing the Prandtl number (Pr = mu * c_p / k), I've noticed that each of these values are just slightly different than all of my textbooks---i.e., not quite enough to appreciably notice.  Interestingly enough though, the combined difference in values when multiplying results in a more pronounced difference for the Prandtl number.  Also, I checked the sources for my five textbooks.  Four of the five have collected their data from different sources (two texts used the same source), yet all have nearly identical (but not quite exact) Prandtl number values.  I'm still curious why there is a difference from PubChem.  Sorry for nitpicking. :)

**Comment by CalebBell** [comment]
Hi,
For about 100 common chemicals, highly accurate properties are available through published papers providing what are called Helmholtz equations of state; and associated transport property models are available for most of them as well.

The CoolProp library implements an impressive amount of the most accurate of them, and `thermo` uses it if installed. You don't appear to have it - you will find more accurate properties for those pure chemicals with it. Since CoolProp provides such accurate values, I have never seen a need for thermo's own correlations to be provide more accuracy for those compounds.

I recommend you install CoolProp with the following command:
`pip install CoolProp`

Cheers,
Caleb

**Comment by archeryguru2000** [comment]
Thanks so much for your quick reply.  I have installed the CoolProp library and now the Prandtl numbers appear much closer to the textbook values.  This (thermo + CoolProp) will be a great addition to my studies and research.  Thanks for your contributions to the community.
