### ISSUE TITLE
Henry's law constant

### ISSUE THREAD

**Issue by ma-sadeghi** [CalebBell/thermo#32]
Hi,

I wonder if I can use your package to get Henry's law constant for gaseous species in water (or other systems).

Best,
Amin

**Comment by CalebBell** [comment]
Hi Amin,

It has not been coded so far, primarily due to a lack of convenient data. The best data for water is in (https://www.atmos-chem-phys.net/15/4399/2015/) but it is a compilation only - it does not provide recommended values.

For other solvents, the data would need to be regressed from the literature.

Sincerely,
Caleb

**Comment by ma-sadeghi** [comment]
Hi Caleb,

Thank you for your quick reply, and also for the reference. On another note - although irrelevant - if I have a large numpy array of temperature values (say a million-element long), other than calling `thermo` in a `for` loop, is there a vectorized way to extract properties from `thermo`? 

Many thanks,
Amin
