### ISSUE TITLE
water heat capacity should be 4184 J/kg/K, but it gives 1782.29...

### ISSUE THREAD

**Issue by jtzhangjuul** [CalebBell/thermo#74]
Hi, trying to calculate water specific heat, and found this error.

```
    subt = Chemical('water')
    subt.calculate(T=273+20, P=1e5)
    subt.Cpl
```

**Comment by CalebBell** [comment]
Hi Jian,
I may need to develop an issue template now to gather basic information from users. Please upgrade your thermo version, try it again, and if it still doesn't work post:

What OS you use, your Python version, and your installed thermo, chemicals, and fluids versions.

**Comment by jtzhangjuul** [comment]
Hi Caleb,
Thank you for getting back to me. Here is the info on this issue.

windows10, python 3.8 with Anaconda3, thermo  0.1.40  

I installed it with 'conda install -c conda-forge thermo', but somehow it stuck with 0.1.40 version, and doesn't allow me to update to 0.2.3

Any suggestion to upgrade to the latest version is appriciated!

**Comment by CalebBell** [comment]
Hi Jian,
It is indeed a bug in an old version of thermo.
I can't help you with conda - it can be complicated sometimes.
I suggest either uninstalling anaconda, and installing it again; or uninstalling `thermo` and `fluids` with conda, and installing them with pip.

I am closing the issue as it has since been fixed.

**Comment by jtzhangjuul** [comment]
Thank you very much! pip install fixed the version issue, and cp value looks correct in 0.2.3  :)
